[project]
name = "badbits"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "moondream>=0.0.6",
    "opencv-python>=4.11.0.86",
    "pillow>=10.4.0",
]
